

-- c_isum2 :: Int -> Int -> Int
-- c_isum3 :: Int -> Int -> Int -> Int

-- | These are identity c functions, i.e. for testing/benchmarking
-- function calls (possibly compiled) to C
idNames = [
  ("signedchar_id",          "signed char"),
  ("unsignedchar_id",        "unsigned char"),
  ("shortint_id",            "short int"),
  ("signedshort_id",         "signed short"),
  ("signedshortint_id",      "signed short int"),
  ("unsignedshort_id",       "unsigned short"),
  ("unsignedshortint_id",    "unsigned short int"),
  ("signedint_id",           "signed int"),
  ("unsignedint_id",         "unsigned int"),
  ("longint_id",             "long int"),
  ("signedlong_id",          "signed long"),
  ("signedlongint_id",       "signed long int"),
  ("unsignedlong_id",        "unsigned long"),
  ("unsignedlongint_id",     "unsigned long int"),
  ("longlong_id",            "long long"),
  ("longlongint_id",         "long long int"),
  ("signedlonglong_id",      "signed long long"),
  ("signedlonglongint_id",   "signed long long int"),
  ("unsignedlonglong_id",    "unsigned long long"),
  ("unsignedlonglongint_id", "unsigned long long int"),
  ("longdouble_id",          "long double")]


-- | Each object is of the form (function_name, type_of_first_arg)
-- In the file, simple_tests.c, each function takes two arguments and returns the first
-- (This is for testing the parsing/compiling for type errors)
-- ("a_ignoring_b","a a_ignoring_b(a x, b y){return x;}\n")
constNames :: [(String, String)]
constNames = [
  ("signedchar_ignoring_signedchar","signed char"),
  ("signedchar_ignoring_unsignedchar","signed char"),
  ("signedchar_ignoring_shortint","signed char"),
  ("signedchar_ignoring_signedshort","signed char"),
  ("signedchar_ignoring_signedshortint","signed char"),
  ("signedchar_ignoring_unsignedshort","signed char"),
  ("signedchar_ignoring_unsignedshortint","signed char"),
  ("signedchar_ignoring_signedint","signed char"),
  ("signedchar_ignoring_unsignedint","signed char"),
  ("signedchar_ignoring_longint","signed char"),
  ("signedchar_ignoring_signedlong","signed char"),
  ("signedchar_ignoring_signedlongint","signed char"),
  ("signedchar_ignoring_unsignedlong","signed char"),
  ("signedchar_ignoring_unsignedlongint","signed char"),
  ("signedchar_ignoring_longlong","signed char"),
  ("signedchar_ignoring_longlongint","signed char"),
  ("signedchar_ignoring_signedlonglong","signed char"),
  ("signedchar_ignoring_signedlonglongint","signed char"),
  ("signedchar_ignoring_unsignedlonglong","signed char"),
  ("signedchar_ignoring_unsignedlonglongint","signed char"),
  ("signedchar_ignoring_longdouble","signed char"),
  ("unsignedchar_ignoring_signedchar","unsigned char"),
  ("unsignedchar_ignoring_unsignedchar","unsigned char"),
  ("unsignedchar_ignoring_shortint","unsigned char"),
  ("unsignedchar_ignoring_signedshort","unsigned char"),
  ("unsignedchar_ignoring_signedshortint","unsigned char"),
  ("unsignedchar_ignoring_unsignedshort","unsigned char"),
  ("unsignedchar_ignoring_unsignedshortint","unsigned char"),
  ("unsignedchar_ignoring_signedint","unsigned char"),
  ("unsignedchar_ignoring_unsignedint","unsigned char"),
  ("unsignedchar_ignoring_longint","unsigned char"),
  ("unsignedchar_ignoring_signedlong","unsigned char"),
  ("unsignedchar_ignoring_signedlongint","unsigned char"),
  ("unsignedchar_ignoring_unsignedlong","unsigned char"),
  ("unsignedchar_ignoring_unsignedlongint","unsigned char"),
  ("unsignedchar_ignoring_longlong","unsigned char"),
  ("unsignedchar_ignoring_longlongint","unsigned char"),
  ("unsignedchar_ignoring_signedlonglong","unsigned char"),
  ("unsignedchar_ignoring_signedlonglongint","unsigned char"),
  ("unsignedchar_ignoring_unsignedlonglong","unsigned char"),
  ("unsignedchar_ignoring_unsignedlonglongint","unsigned char"),
  ("unsignedchar_ignoring_longdouble","unsigned char"),
  ("shortint_ignoring_signedchar","short int"),
  ("shortint_ignoring_unsignedchar","short int"),
  ("shortint_ignoring_shortint","short int"),
  ("shortint_ignoring_signedshort","short int"),
  ("shortint_ignoring_signedshortint","short int"),
  ("shortint_ignoring_unsignedshort","short int"),
  ("shortint_ignoring_unsignedshortint","short int"),
  ("shortint_ignoring_signedint","short int"),
  ("shortint_ignoring_unsignedint","short int"),
  ("shortint_ignoring_longint","short int"),
  ("shortint_ignoring_signedlong","short int"),
  ("shortint_ignoring_signedlongint","short int"),
  ("shortint_ignoring_unsignedlong","short int"),
  ("shortint_ignoring_unsignedlongint","short int"),
  ("shortint_ignoring_longlong","short int"),
  ("shortint_ignoring_longlongint","short int"),
  ("shortint_ignoring_signedlonglong","short int"),
  ("shortint_ignoring_signedlonglongint","short int"),
  ("shortint_ignoring_unsignedlonglong","short int"),
  ("shortint_ignoring_unsignedlonglongint","short int"),
  ("shortint_ignoring_longdouble","short int"),
  ("signedshort_ignoring_signedchar","signed short"),
  ("signedshort_ignoring_unsignedchar","signed short"),
  ("signedshort_ignoring_shortint","signed short"),
  ("signedshort_ignoring_signedshort","signed short"),
  ("signedshort_ignoring_signedshortint","signed short"),
  ("signedshort_ignoring_unsignedshort","signed short"),
  ("signedshort_ignoring_unsignedshortint","signed short"),
  ("signedshort_ignoring_signedint","signed short"),
  ("signedshort_ignoring_unsignedint","signed short"),
  ("signedshort_ignoring_longint","signed short"),
  ("signedshort_ignoring_signedlong","signed short"),
  ("signedshort_ignoring_signedlongint","signed short"),
  ("signedshort_ignoring_unsignedlong","signed short"),
  ("signedshort_ignoring_unsignedlongint","signed short"),
  ("signedshort_ignoring_longlong","signed short"),
  ("signedshort_ignoring_longlongint","signed short"),
  ("signedshort_ignoring_signedlonglong","signed short"),
  ("signedshort_ignoring_signedlonglongint","signed short"),
  ("signedshort_ignoring_unsignedlonglong","signed short"),
  ("signedshort_ignoring_unsignedlonglongint","signed short"),
  ("signedshort_ignoring_longdouble","signed short"),
  ("signedshortint_ignoring_signedchar","signed short int"),
  ("signedshortint_ignoring_unsignedchar","signed short int"),
  ("signedshortint_ignoring_shortint","signed short int"),
  ("signedshortint_ignoring_signedshort","signed short int"),
  ("signedshortint_ignoring_signedshortint","signed short int"),
  ("signedshortint_ignoring_unsignedshort","signed short int"),
  ("signedshortint_ignoring_unsignedshortint","signed short int"),
  ("signedshortint_ignoring_signedint","signed short int"),
  ("signedshortint_ignoring_unsignedint","signed short int"),
  ("signedshortint_ignoring_longint","signed short int"),
  ("signedshortint_ignoring_signedlong","signed short int"),
  ("signedshortint_ignoring_signedlongint","signed short int"),
  ("signedshortint_ignoring_unsignedlong","signed short int"),
  ("signedshortint_ignoring_unsignedlongint","signed short int"),
  ("signedshortint_ignoring_longlong","signed short int"),
  ("signedshortint_ignoring_longlongint","signed short int"),
  ("signedshortint_ignoring_signedlonglong","signed short int"),
  ("signedshortint_ignoring_signedlonglongint","signed short int"),
  ("signedshortint_ignoring_unsignedlonglong","signed short int"),
  ("signedshortint_ignoring_unsignedlonglongint","signed short int"),
  ("signedshortint_ignoring_longdouble","signed short int"),
  ("unsignedshort_ignoring_signedchar","unsigned short"),
  ("unsignedshort_ignoring_unsignedchar","unsigned short"),
  ("unsignedshort_ignoring_shortint","unsigned short"),
  ("unsignedshort_ignoring_signedshort","unsigned short"),
  ("unsignedshort_ignoring_signedshortint","unsigned short"),
  ("unsignedshort_ignoring_unsignedshort","unsigned short"),
  ("unsignedshort_ignoring_unsignedshortint","unsigned short"),
  ("unsignedshort_ignoring_signedint","unsigned short"),
  ("unsignedshort_ignoring_unsignedint","unsigned short"),
  ("unsignedshort_ignoring_longint","unsigned short"),
  ("unsignedshort_ignoring_signedlong","unsigned short"),
  ("unsignedshort_ignoring_signedlongint","unsigned short"),
  ("unsignedshort_ignoring_unsignedlong","unsigned short"),
  ("unsignedshort_ignoring_unsignedlongint","unsigned short"),
  ("unsignedshort_ignoring_longlong","unsigned short"),
  ("unsignedshort_ignoring_longlongint","unsigned short"),
  ("unsignedshort_ignoring_signedlonglong","unsigned short"),
  ("unsignedshort_ignoring_signedlonglongint","unsigned short"),
  ("unsignedshort_ignoring_unsignedlonglong","unsigned short"),
  ("unsignedshort_ignoring_unsignedlonglongint","unsigned short"),
  ("unsignedshort_ignoring_longdouble","unsigned short"),
  ("unsignedshortint_ignoring_signedchar","unsigned short int"),
  ("unsignedshortint_ignoring_unsignedchar","unsigned short int"),
  ("unsignedshortint_ignoring_shortint","unsigned short int"),
  ("unsignedshortint_ignoring_signedshort","unsigned short int"),
  ("unsignedshortint_ignoring_signedshortint","unsigned short int"),
  ("unsignedshortint_ignoring_unsignedshort","unsigned short int"),
  ("unsignedshortint_ignoring_unsignedshortint","unsigned short int"),
  ("unsignedshortint_ignoring_signedint","unsigned short int"),
  ("unsignedshortint_ignoring_unsignedint","unsigned short int"),
  ("unsignedshortint_ignoring_longint","unsigned short int"),
  ("unsignedshortint_ignoring_signedlong","unsigned short int"),
  ("unsignedshortint_ignoring_signedlongint","unsigned short int"),
  ("unsignedshortint_ignoring_unsignedlong","unsigned short int"),
  ("unsignedshortint_ignoring_unsignedlongint","unsigned short int"),
  ("unsignedshortint_ignoring_longlong","unsigned short int"),
  ("unsignedshortint_ignoring_longlongint","unsigned short int"),
  ("unsignedshortint_ignoring_signedlonglong","unsigned short int"),
  ("unsignedshortint_ignoring_signedlonglongint","unsigned short int"),
  ("unsignedshortint_ignoring_unsignedlonglong","unsigned short int"),
  ("unsignedshortint_ignoring_unsignedlonglongint","unsigned short int"),
  ("unsignedshortint_ignoring_longdouble","unsigned short int"),
  ("signedint_ignoring_signedchar","signed int"),
  ("signedint_ignoring_unsignedchar","signed int"),
  ("signedint_ignoring_shortint","signed int"),
  ("signedint_ignoring_signedshort","signed int"),
  ("signedint_ignoring_signedshortint","signed int"),
  ("signedint_ignoring_unsignedshort","signed int"),
  ("signedint_ignoring_unsignedshortint","signed int"),
  ("signedint_ignoring_signedint","signed int"),
  ("signedint_ignoring_unsignedint","signed int"),
  ("signedint_ignoring_longint","signed int"),
  ("signedint_ignoring_signedlong","signed int"),
  ("signedint_ignoring_signedlongint","signed int"),
  ("signedint_ignoring_unsignedlong","signed int"),
  ("signedint_ignoring_unsignedlongint","signed int"),
  ("signedint_ignoring_longlong","signed int"),
  ("signedint_ignoring_longlongint","signed int"),
  ("signedint_ignoring_signedlonglong","signed int"),
  ("signedint_ignoring_signedlonglongint","signed int"),
  ("signedint_ignoring_unsignedlonglong","signed int"),
  ("signedint_ignoring_unsignedlonglongint","signed int"),
  ("signedint_ignoring_longdouble","signed int"),
  ("unsignedint_ignoring_signedchar","unsigned int"),
  ("unsignedint_ignoring_unsignedchar","unsigned int"),
  ("unsignedint_ignoring_shortint","unsigned int"),
  ("unsignedint_ignoring_signedshort","unsigned int"),
  ("unsignedint_ignoring_signedshortint","unsigned int"),
  ("unsignedint_ignoring_unsignedshort","unsigned int"),
  ("unsignedint_ignoring_unsignedshortint","unsigned int"),
  ("unsignedint_ignoring_signedint","unsigned int"),
  ("unsignedint_ignoring_unsignedint","unsigned int"),
  ("unsignedint_ignoring_longint","unsigned int"),
  ("unsignedint_ignoring_signedlong","unsigned int"),
  ("unsignedint_ignoring_signedlongint","unsigned int"),
  ("unsignedint_ignoring_unsignedlong","unsigned int"),
  ("unsignedint_ignoring_unsignedlongint","unsigned int"),
  ("unsignedint_ignoring_longlong","unsigned int"),
  ("unsignedint_ignoring_longlongint","unsigned int"),
  ("unsignedint_ignoring_signedlonglong","unsigned int"),
  ("unsignedint_ignoring_signedlonglongint","unsigned int"),
  ("unsignedint_ignoring_unsignedlonglong","unsigned int"),
  ("unsignedint_ignoring_unsignedlonglongint","unsigned int"),
  ("unsignedint_ignoring_longdouble","unsigned int"),
  ("longint_ignoring_signedchar","long int"),
  ("longint_ignoring_unsignedchar","long int"),
  ("longint_ignoring_shortint","long int"),
  ("longint_ignoring_signedshort","long int"),
  ("longint_ignoring_signedshortint","long int"),
  ("longint_ignoring_unsignedshort","long int"),
  ("longint_ignoring_unsignedshortint","long int"),
  ("longint_ignoring_signedint","long int"),
  ("longint_ignoring_unsignedint","long int"),
  ("longint_ignoring_longint","long int"),
  ("longint_ignoring_signedlong","long int"),
  ("longint_ignoring_signedlongint","long int"),
  ("longint_ignoring_unsignedlong","long int"),
  ("longint_ignoring_unsignedlongint","long int"),
  ("longint_ignoring_longlong","long int"),
  ("longint_ignoring_longlongint","long int"),
  ("longint_ignoring_signedlonglong","long int"),
  ("longint_ignoring_signedlonglongint","long int"),
  ("longint_ignoring_unsignedlonglong","long int"),
  ("longint_ignoring_unsignedlonglongint","long int"),
  ("longint_ignoring_longdouble","long int"),
  ("signedlong_ignoring_signedchar","signed long"),
  ("signedlong_ignoring_unsignedchar","signed long"),
  ("signedlong_ignoring_shortint","signed long"),
  ("signedlong_ignoring_signedshort","signed long"),
  ("signedlong_ignoring_signedshortint","signed long"),
  ("signedlong_ignoring_unsignedshort","signed long"),
  ("signedlong_ignoring_unsignedshortint","signed long"),
  ("signedlong_ignoring_signedint","signed long"),
  ("signedlong_ignoring_unsignedint","signed long"),
  ("signedlong_ignoring_longint","signed long"),
  ("signedlong_ignoring_signedlong","signed long"),
  ("signedlong_ignoring_signedlongint","signed long"),
  ("signedlong_ignoring_unsignedlong","signed long"),
  ("signedlong_ignoring_unsignedlongint","signed long"),
  ("signedlong_ignoring_longlong","signed long"),
  ("signedlong_ignoring_longlongint","signed long"),
  ("signedlong_ignoring_signedlonglong","signed long"),
  ("signedlong_ignoring_signedlonglongint","signed long"),
  ("signedlong_ignoring_unsignedlonglong","signed long"),
  ("signedlong_ignoring_unsignedlonglongint","signed long"),
  ("signedlong_ignoring_longdouble","signed long"),
  ("signedlongint_ignoring_signedchar","signed long int"),
  ("signedlongint_ignoring_unsignedchar","signed long int"),
  ("signedlongint_ignoring_shortint","signed long int"),
  ("signedlongint_ignoring_signedshort","signed long int"),
  ("signedlongint_ignoring_signedshortint","signed long int"),
  ("signedlongint_ignoring_unsignedshort","signed long int"),
  ("signedlongint_ignoring_unsignedshortint","signed long int"),
  ("signedlongint_ignoring_signedint","signed long int"),
  ("signedlongint_ignoring_unsignedint","signed long int"),
  ("signedlongint_ignoring_longint","signed long int"),
  ("signedlongint_ignoring_signedlong","signed long int"),
  ("signedlongint_ignoring_signedlongint","signed long int"),
  ("signedlongint_ignoring_unsignedlong","signed long int"),
  ("signedlongint_ignoring_unsignedlongint","signed long int"),
  ("signedlongint_ignoring_longlong","signed long int"),
  ("signedlongint_ignoring_longlongint","signed long int"),
  ("signedlongint_ignoring_signedlonglong","signed long int"),
  ("signedlongint_ignoring_signedlonglongint","signed long int"),
  ("signedlongint_ignoring_unsignedlonglong","signed long int"),
  ("signedlongint_ignoring_unsignedlonglongint","signed long int"),
  ("signedlongint_ignoring_longdouble","signed long int"),
  ("unsignedlong_ignoring_signedchar","unsigned long"),
  ("unsignedlong_ignoring_unsignedchar","unsigned long"),
  ("unsignedlong_ignoring_shortint","unsigned long"),
  ("unsignedlong_ignoring_signedshort","unsigned long"),
  ("unsignedlong_ignoring_signedshortint","unsigned long"),
  ("unsignedlong_ignoring_unsignedshort","unsigned long"),
  ("unsignedlong_ignoring_unsignedshortint","unsigned long"),
  ("unsignedlong_ignoring_signedint","unsigned long"),
  ("unsignedlong_ignoring_unsignedint","unsigned long"),
  ("unsignedlong_ignoring_longint","unsigned long"),
  ("unsignedlong_ignoring_signedlong","unsigned long"),
  ("unsignedlong_ignoring_signedlongint","unsigned long"),
  ("unsignedlong_ignoring_unsignedlong","unsigned long"),
  ("unsignedlong_ignoring_unsignedlongint","unsigned long"),
  ("unsignedlong_ignoring_longlong","unsigned long"),
  ("unsignedlong_ignoring_longlongint","unsigned long"),
  ("unsignedlong_ignoring_signedlonglong","unsigned long"),
  ("unsignedlong_ignoring_signedlonglongint","unsigned long"),
  ("unsignedlong_ignoring_unsignedlonglong","unsigned long"),
  ("unsignedlong_ignoring_unsignedlonglongint","unsigned long"),
  ("unsignedlong_ignoring_longdouble","unsigned long"),
  ("unsignedlongint_ignoring_signedchar","unsigned long int"),
  ("unsignedlongint_ignoring_unsignedchar","unsigned long int"),
  ("unsignedlongint_ignoring_shortint","unsigned long int"),
  ("unsignedlongint_ignoring_signedshort","unsigned long int"),
  ("unsignedlongint_ignoring_signedshortint","unsigned long int"),
  ("unsignedlongint_ignoring_unsignedshort","unsigned long int"),
  ("unsignedlongint_ignoring_unsignedshortint","unsigned long int"),
  ("unsignedlongint_ignoring_signedint","unsigned long int"),
  ("unsignedlongint_ignoring_unsignedint","unsigned long int"),
  ("unsignedlongint_ignoring_longint","unsigned long int"),
  ("unsignedlongint_ignoring_signedlong","unsigned long int"),
  ("unsignedlongint_ignoring_signedlongint","unsigned long int"),
  ("unsignedlongint_ignoring_unsignedlong","unsigned long int"),
  ("unsignedlongint_ignoring_unsignedlongint","unsigned long int"),
  ("unsignedlongint_ignoring_longlong","unsigned long int"),
  ("unsignedlongint_ignoring_longlongint","unsigned long int"),
  ("unsignedlongint_ignoring_signedlonglong","unsigned long int"),
  ("unsignedlongint_ignoring_signedlonglongint","unsigned long int"),
  ("unsignedlongint_ignoring_unsignedlonglong","unsigned long int"),
  ("unsignedlongint_ignoring_unsignedlonglongint","unsigned long int"),
  ("unsignedlongint_ignoring_longdouble","unsigned long int"),
  ("longlong_ignoring_signedchar","long long"),
  ("longlong_ignoring_unsignedchar","long long"),
  ("longlong_ignoring_shortint","long long"),
  ("longlong_ignoring_signedshort","long long"),
  ("longlong_ignoring_signedshortint","long long"),
  ("longlong_ignoring_unsignedshort","long long"),
  ("longlong_ignoring_unsignedshortint","long long"),
  ("longlong_ignoring_signedint","long long"),
  ("longlong_ignoring_unsignedint","long long"),
  ("longlong_ignoring_longint","long long"),
  ("longlong_ignoring_signedlong","long long"),
  ("longlong_ignoring_signedlongint","long long"),
  ("longlong_ignoring_unsignedlong","long long"),
  ("longlong_ignoring_unsignedlongint","long long"),
  ("longlong_ignoring_longlong","long long"),
  ("longlong_ignoring_longlongint","long long"),
  ("longlong_ignoring_signedlonglong","long long"),
  ("longlong_ignoring_signedlonglongint","long long"),
  ("longlong_ignoring_unsignedlonglong","long long"),
  ("longlong_ignoring_unsignedlonglongint","long long"),
  ("longlong_ignoring_longdouble","long long"),
  ("longlongint_ignoring_signedchar","long long int"),
  ("longlongint_ignoring_unsignedchar","long long int"),
  ("longlongint_ignoring_shortint","long long int"),
  ("longlongint_ignoring_signedshort","long long int"),
  ("longlongint_ignoring_signedshortint","long long int"),
  ("longlongint_ignoring_unsignedshort","long long int"),
  ("longlongint_ignoring_unsignedshortint","long long int"),
  ("longlongint_ignoring_signedint","long long int"),
  ("longlongint_ignoring_unsignedint","long long int"),
  ("longlongint_ignoring_longint","long long int"),
  ("longlongint_ignoring_signedlong","long long int"),
  ("longlongint_ignoring_signedlongint","long long int"),
  ("longlongint_ignoring_unsignedlong","long long int"),
  ("longlongint_ignoring_unsignedlongint","long long int"),
  ("longlongint_ignoring_longlong","long long int"),
  ("longlongint_ignoring_longlongint","long long int"),
  ("longlongint_ignoring_signedlonglong","long long int"),
  ("longlongint_ignoring_signedlonglongint","long long int"),
  ("longlongint_ignoring_unsignedlonglong","long long int"),
  ("longlongint_ignoring_unsignedlonglongint","long long int"),
  ("longlongint_ignoring_longdouble","long long int"),
  ("signedlonglong_ignoring_signedchar","signed long long"),
  ("signedlonglong_ignoring_unsignedchar","signed long long"),
  ("signedlonglong_ignoring_shortint","signed long long"),
  ("signedlonglong_ignoring_signedshort","signed long long"),
  ("signedlonglong_ignoring_signedshortint","signed long long"),
  ("signedlonglong_ignoring_unsignedshort","signed long long"),
  ("signedlonglong_ignoring_unsignedshortint","signed long long"),
  ("signedlonglong_ignoring_signedint","signed long long"),
  ("signedlonglong_ignoring_unsignedint","signed long long"),
  ("signedlonglong_ignoring_longint","signed long long"),
  ("signedlonglong_ignoring_signedlong","signed long long"),
  ("signedlonglong_ignoring_signedlongint","signed long long"),
  ("signedlonglong_ignoring_unsignedlong","signed long long"),
  ("signedlonglong_ignoring_unsignedlongint","signed long long"),
  ("signedlonglong_ignoring_longlong","signed long long"),
  ("signedlonglong_ignoring_longlongint","signed long long"),
  ("signedlonglong_ignoring_signedlonglong","signed long long"),
  ("signedlonglong_ignoring_signedlonglongint","signed long long"),
  ("signedlonglong_ignoring_unsignedlonglong","signed long long"),
  ("signedlonglong_ignoring_unsignedlonglongint","signed long long"),
  ("signedlonglong_ignoring_longdouble","signed long long"),
  ("signedlonglongint_ignoring_signedchar","signed long long int"),
  ("signedlonglongint_ignoring_unsignedchar","signed long long int"),
  ("signedlonglongint_ignoring_shortint","signed long long int"),
  ("signedlonglongint_ignoring_signedshort","signed long long int"),
  ("signedlonglongint_ignoring_signedshortint","signed long long int"),
  ("signedlonglongint_ignoring_unsignedshort","signed long long int"),
  ("signedlonglongint_ignoring_unsignedshortint","signed long long int"),
  ("signedlonglongint_ignoring_signedint","signed long long int"),
  ("signedlonglongint_ignoring_unsignedint","signed long long int"),
  ("signedlonglongint_ignoring_longint","signed long long int"),
  ("signedlonglongint_ignoring_signedlong","signed long long int"),
  ("signedlonglongint_ignoring_signedlongint","signed long long int"),
  ("signedlonglongint_ignoring_unsignedlong","signed long long int"),
  ("signedlonglongint_ignoring_unsignedlongint","signed long long int"),
  ("signedlonglongint_ignoring_longlong","signed long long int"),
  ("signedlonglongint_ignoring_longlongint","signed long long int"),
  ("signedlonglongint_ignoring_signedlonglong","signed long long int"),
  ("signedlonglongint_ignoring_signedlonglongint","signed long long int"),
  ("signedlonglongint_ignoring_unsignedlonglong","signed long long int"),
  ("signedlonglongint_ignoring_unsignedlonglongint","signed long long int"),
  ("signedlonglongint_ignoring_longdouble","signed long long int"),
  ("unsignedlonglong_ignoring_signedchar","unsigned long long"),
  ("unsignedlonglong_ignoring_unsignedchar","unsigned long long"),
  ("unsignedlonglong_ignoring_shortint","unsigned long long"),
  ("unsignedlonglong_ignoring_signedshort","unsigned long long"),
  ("unsignedlonglong_ignoring_signedshortint","unsigned long long"),
  ("unsignedlonglong_ignoring_unsignedshort","unsigned long long"),
  ("unsignedlonglong_ignoring_unsignedshortint","unsigned long long"),
  ("unsignedlonglong_ignoring_signedint","unsigned long long"),
  ("unsignedlonglong_ignoring_unsignedint","unsigned long long"),
  ("unsignedlonglong_ignoring_longint","unsigned long long"),
  ("unsignedlonglong_ignoring_signedlong","unsigned long long"),
  ("unsignedlonglong_ignoring_signedlongint","unsigned long long"),
  ("unsignedlonglong_ignoring_unsignedlong","unsigned long long"),
  ("unsignedlonglong_ignoring_unsignedlongint","unsigned long long"),
  ("unsignedlonglong_ignoring_longlong","unsigned long long"),
  ("unsignedlonglong_ignoring_longlongint","unsigned long long"),
  ("unsignedlonglong_ignoring_signedlonglong","unsigned long long"),
  ("unsignedlonglong_ignoring_signedlonglongint","unsigned long long"),
  ("unsignedlonglong_ignoring_unsignedlonglong","unsigned long long"),
  ("unsignedlonglong_ignoring_unsignedlonglongint","unsigned long long"),
  ("unsignedlonglong_ignoring_longdouble","unsigned long long"),
  ("unsignedlonglongint_ignoring_signedchar","unsigned long long int"),
  ("unsignedlonglongint_ignoring_unsignedchar","unsigned long long int"),
  ("unsignedlonglongint_ignoring_shortint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_signedshort","unsigned long long int"),
  ("unsignedlonglongint_ignoring_signedshortint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_unsignedshort","unsigned long long int"),
  ("unsignedlonglongint_ignoring_unsignedshortint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_signedint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_unsignedint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_longint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_signedlong","unsigned long long int"),
  ("unsignedlonglongint_ignoring_signedlongint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_unsignedlong","unsigned long long int"),
  ("unsignedlonglongint_ignoring_unsignedlongint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_longlong","unsigned long long int"),
  ("unsignedlonglongint_ignoring_longlongint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_signedlonglong","unsigned long long int"),
  ("unsignedlonglongint_ignoring_signedlonglongint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_unsignedlonglong","unsigned long long int"),
  ("unsignedlonglongint_ignoring_unsignedlonglongint","unsigned long long int"),
  ("unsignedlonglongint_ignoring_longdouble","unsigned long long int"),
  ("longdouble_ignoring_signedchar","long double"),
  ("longdouble_ignoring_unsignedchar","long double"),
  ("longdouble_ignoring_shortint","long double"),
  ("longdouble_ignoring_signedshort","long double"),
  ("longdouble_ignoring_signedshortint","long double"),
  ("longdouble_ignoring_unsignedshort","long double"),
  ("longdouble_ignoring_unsignedshortint","long double"),
  ("longdouble_ignoring_signedint","long double"),
  ("longdouble_ignoring_unsignedint","long double"),
  ("longdouble_ignoring_longint","long double"),
  ("longdouble_ignoring_signedlong","long double"),
  ("longdouble_ignoring_signedlongint","long double"),
  ("longdouble_ignoring_unsignedlong","long double"),
  ("longdouble_ignoring_unsignedlongint","long double"),
  ("longdouble_ignoring_longlong","long double"),
  ("longdouble_ignoring_longlongint","long double"),
  ("longdouble_ignoring_signedlonglong","long double"),
  ("longdouble_ignoring_signedlonglongint","long double"),
  ("longdouble_ignoring_unsignedlonglong","long double"),
  ("longdouble_ignoring_unsignedlonglongint","long double"),
  ("longdouble_ignoring_longdouble","long double")]
